const { contextBridge, ipcRenderer } = require('electron');

// No nodeIntegration in the renderer — this is the only bridge. Every TNC
// connection, serial port, and raw socket lives in the main process.
contextBridge.exposeInMainWorld('nexdigi', {
  listSerialPorts: () => ipcRenderer.invoke('serial:list'),

  listTncs: () => ipcRenderer.invoke('tnc:list'),
  createTnc: (config) => ipcRenderer.invoke('tnc:create', config),
  updateTnc: (tncId, patch) => ipcRenderer.invoke('tnc:update', tncId, patch),
  removeTnc: (tncId) => ipcRenderer.invoke('tnc:remove', tncId),
  connectTnc: (tncId) => ipcRenderer.invoke('tnc:connect', tncId),
  disconnectTnc: (tncId) => ipcRenderer.invoke('tnc:disconnect', tncId),

  addRadio: (tncId, radio) => ipcRenderer.invoke('radio:add', tncId, radio),
  removeRadio: (tncId, radioId) => ipcRenderer.invoke('radio:remove', tncId, radioId),

  sendUnproto: (tncId, radioId, dest, text) => ipcRenderer.invoke('terminal:sendUnproto', tncId, radioId, dest, text),
  startSession: (tncId, radioId, remoteCall, digiPath, scriptId) => ipcRenderer.invoke('terminal:startSession', tncId, radioId, remoteCall, digiPath, scriptId),
  sendSessionText: (sessionId, text) => ipcRenderer.invoke('terminal:sendSessionText', sessionId, text),
  endSession: (sessionId) => ipcRenderer.invoke('terminal:endSession', sessionId),

  pickFileToSend: () => ipcRenderer.invoke('terminal:pickFileToSend'),
  pickSaveLocation: (suggestedName) => ipcRenderer.invoke('terminal:pickSaveLocation', suggestedName),
  sendFile: (sessionId, filePath) => ipcRenderer.invoke('terminal:sendFile', sessionId, filePath),
  respondFileOffer: (sessionId, accept, savePath) => ipcRenderer.invoke('terminal:respondFileOffer', sessionId, accept, savePath),
  abortFileTransfer: (sessionId) => ipcRenderer.invoke('terminal:abortFileTransfer', sessionId),

  listScripts: () => ipcRenderer.invoke('scripts:list'),
  saveScript: (script) => ipcRenderer.invoke('scripts:save', script),
  deleteScript: (scriptId) => ipcRenderer.invoke('scripts:delete', scriptId),
  runScript: (sessionId, scriptId) => ipcRenderer.invoke('scripts:run', sessionId, scriptId),
  abortScript: (sessionId) => ipcRenderer.invoke('scripts:abort', sessionId),

  onMonitor: (cb) => { const l = (_e, evt) => cb(evt); ipcRenderer.on('monitor', l); return () => ipcRenderer.removeListener('monitor', l); },
  onTncStatus: (cb) => { const l = (_e, evt) => cb(evt); ipcRenderer.on('tnc-status', l); return () => ipcRenderer.removeListener('tnc-status', l); },
  onTncListChanged: (cb) => { const l = () => cb(); ipcRenderer.on('tnc-list-changed', l); return () => ipcRenderer.removeListener('tnc-list-changed', l); },
  onSessionState: (cb) => { const l = (_e, evt) => cb(evt); ipcRenderer.on('session-state', l); return () => ipcRenderer.removeListener('session-state', l); },
  onSessionData: (cb) => { const l = (_e, evt) => cb(evt); ipcRenderer.on('session-data', l); return () => ipcRenderer.removeListener('session-data', l); },
  onSessionTx: (cb) => { const l = (_e, evt) => cb(evt); ipcRenderer.on('session-tx', l); return () => ipcRenderer.removeListener('session-tx', l); },
  onSessionError: (cb) => { const l = (_e, evt) => cb(evt); ipcRenderer.on('session-error', l); return () => ipcRenderer.removeListener('session-error', l); },
  onFileTransferOffer: (cb) => { const l = (_e, evt) => cb(evt); ipcRenderer.on('file-transfer-offer', l); return () => ipcRenderer.removeListener('file-transfer-offer', l); },
  onFileTransferProgress: (cb) => { const l = (_e, evt) => cb(evt); ipcRenderer.on('file-transfer-progress', l); return () => ipcRenderer.removeListener('file-transfer-progress', l); },
  onFileTransferComplete: (cb) => { const l = (_e, evt) => cb(evt); ipcRenderer.on('file-transfer-complete', l); return () => ipcRenderer.removeListener('file-transfer-complete', l); },
  onFileTransferError: (cb) => { const l = (_e, evt) => cb(evt); ipcRenderer.on('file-transfer-error', l); return () => ipcRenderer.removeListener('file-transfer-error', l); },
  onScriptComplete: (cb) => { const l = (_e, evt) => cb(evt); ipcRenderer.on('script-complete', l); return () => ipcRenderer.removeListener('script-complete', l); },
  onScriptError: (cb) => { const l = (_e, evt) => cb(evt); ipcRenderer.on('script-error', l); return () => ipcRenderer.removeListener('script-error', l); },

  // Winlink (bundled pat subprocess)
  winlinkGetSettings: () => ipcRenderer.invoke('winlink:getSettings'),
  winlinkSaveSettings: (settings) => ipcRenderer.invoke('winlink:saveSettings', settings),
  winlinkStart: () => ipcRenderer.invoke('winlink:start'),
  winlinkStop: () => ipcRenderer.invoke('winlink:stop'),
  winlinkListMessages: (folder) => ipcRenderer.invoke('winlink:listMessages', folder),
  winlinkGetMessage: (folder, mid) => ipcRenderer.invoke('winlink:getMessage', folder, mid),
  winlinkMarkRead: (folder, mid, read) => ipcRenderer.invoke('winlink:markRead', folder, mid, read),
  winlinkDeleteMessage: (folder, mid) => ipcRenderer.invoke('winlink:deleteMessage', folder, mid),
  winlinkArchiveMessage: (folder, mid) => ipcRenderer.invoke('winlink:archiveMessage', folder, mid),
  winlinkSendMessage: (message) => ipcRenderer.invoke('winlink:sendMessage', message),
  winlinkGetConnectAliases: () => ipcRenderer.invoke('winlink:getConnectAliases'),
  winlinkSetConnectAlias: (name, url) => ipcRenderer.invoke('winlink:setConnectAlias', name, url),
  winlinkRemoveConnectAlias: (name) => ipcRenderer.invoke('winlink:removeConnectAlias', name),
  winlinkConnect: (url) => ipcRenderer.invoke('winlink:connect', url),
  winlinkDisconnect: (dirty) => ipcRenderer.invoke('winlink:disconnect', dirty),
  winlinkSearchRms: (params) => ipcRenderer.invoke('winlink:searchRms', params),
  onWinlinkLog: (cb) => { const l = (_e, line) => cb(line); ipcRenderer.on('winlink-log', l); return () => ipcRenderer.removeListener('winlink-log', l); },
  onWinlinkStatus: (cb) => { const l = (_e, status) => cb(status); ipcRenderer.on('winlink-status', l); return () => ipcRenderer.removeListener('winlink-status', l); },

  // BBS (NexDigi server REST)
  bbsGetSettings: () => ipcRenderer.invoke('bbs:getSettings'),
  bbsSaveSettings: (settings) => ipcRenderer.invoke('bbs:saveSettings', settings),
  bbsListMessages: (filters) => ipcRenderer.invoke('bbs:listMessages', filters),
  bbsPostMessage: (message) => ipcRenderer.invoke('bbs:postMessage', message),
  bbsMarkRead: (messageNumber) => ipcRenderer.invoke('bbs:markRead', messageNumber),
  bbsDeleteMessage: (messageNumber) => ipcRenderer.invoke('bbs:deleteMessage', messageNumber),
  bbsListBulletins: () => ipcRenderer.invoke('bbs:listBulletins'),
  bbsGetStats: () => ipcRenderer.invoke('bbs:getStats'),
  bbsGetTransport: () => ipcRenderer.invoke('bbsFacade:getTransport'),
  bbsSetTransport: (transport) => ipcRenderer.invoke('bbsFacade:setTransport', transport),
  rfBbsGetSettings: () => ipcRenderer.invoke('rfBbs:getSettings'),
  rfBbsSaveSettings: (settings) => ipcRenderer.invoke('rfBbs:saveSettings', settings),

  // Chat (NexDigi server REST + shared WebSocket)
  chatConnect: () => ipcRenderer.invoke('chat:connect'),
  chatDisconnect: () => ipcRenderer.invoke('chat:disconnect'),
  chatListRooms: () => ipcRenderer.invoke('chat:listRooms'),
  chatCreateRoom: (name, description) => ipcRenderer.invoke('chat:createRoom', name, description),
  chatSwitchRoom: (name) => ipcRenderer.invoke('chat:switchRoom', name),
  chatGetRoomUsers: (name) => ipcRenderer.invoke('chat:getRoomUsers', name),
  chatSendMessage: (text) => ipcRenderer.invoke('chat:sendMessage', text),
  chatSendTyping: (typing) => ipcRenderer.invoke('chat:sendTyping', typing),
  // A single generic event carries every real server message (see
  // ChatManager.js for why — the server's own 'chat-broadcast' wrapper type
  // never actually arrives on the wire; this dispatches on msg.type itself).
  onChatEvent: (cb) => { const l = (_e, evt) => cb(evt); ipcRenderer.on('chat-event', l); return () => ipcRenderer.removeListener('chat-event', l); },
  onChatError: (cb) => { const l = (_e, evt) => cb(evt); ipcRenderer.on('chat-error', l); return () => ipcRenderer.removeListener('chat-error', l); },
  onChatSocketClosed: (cb) => { const l = (_e, evt) => cb(evt); ipcRenderer.on('chat-socket-closed', l); return () => ipcRenderer.removeListener('chat-socket-closed', l); },

  // APRS (RF via TncManager, always-on; APRS-IS optional)
  aprsGetStations: () => ipcRenderer.invoke('aprs:getStations'),
  aprsGetSettings: () => ipcRenderer.invoke('aprs:getSettings'),
  aprsSaveSettings: (settings) => ipcRenderer.invoke('aprs:saveSettings', settings),
  aprsConnectAprsIs: () => ipcRenderer.invoke('aprs:connectAprsIs'),
  aprsDisconnectAprsIs: () => ipcRenderer.invoke('aprs:disconnectAprsIs'),
  aprsGetMyStation: () => ipcRenderer.invoke('aprs:getMyStation'),
  aprsSaveMyStation: (myStation) => ipcRenderer.invoke('aprs:saveMyStation', myStation),
  aprsBeaconNow: () => ipcRenderer.invoke('aprs:beaconNow'),
  aprsSendMessage: (toCallsign, text) => ipcRenderer.invoke('aprs:sendMessage', toCallsign, text),
  aprsCancelMessage: (msgId) => ipcRenderer.invoke('aprs:cancelMessage', msgId),
  aprsGetMessages: () => ipcRenderer.invoke('aprs:getMessages'),
  aprsMarkMessageRead: (id) => ipcRenderer.invoke('aprs:markMessageRead', id),
  aprsCreateObject: (name, opts) => ipcRenderer.invoke('aprs:createObject', name, opts),
  aprsKillObject: (name) => ipcRenderer.invoke('aprs:killObject', name),
  aprsGetObjects: () => ipcRenderer.invoke('aprs:getObjects'),
  getMapTile: (z, x, y) => ipcRenderer.invoke('maps:getTile', z, x, y),
  getMapCacheInfo: () => ipcRenderer.invoke('maps:getCacheInfo'),
  setMapCacheBudget: (bytes) => ipcRenderer.invoke('maps:setCacheBudget', bytes),
  clearMapCache: () => ipcRenderer.invoke('maps:clearCache'),
  onAprsStation: (cb) => { const l = (_e, evt) => cb(evt); ipcRenderer.on('aprs-station', l); return () => ipcRenderer.removeListener('aprs-station', l); },
  onAprsIsStatus: (cb) => { const l = (_e, evt) => cb(evt); ipcRenderer.on('aprs-is-status', l); return () => ipcRenderer.removeListener('aprs-is-status', l); },
  onAprsMessage: (cb) => { const l = (_e, evt) => cb(evt); ipcRenderer.on('aprs-message', l); return () => ipcRenderer.removeListener('aprs-message', l); },
  onAprsObject: (cb) => { const l = (_e, evt) => cb(evt); ipcRenderer.on('aprs-object', l); return () => ipcRenderer.removeListener('aprs-object', l); },
  onAprsBeaconSent: (cb) => { const l = (_e, evt) => cb(evt); ipcRenderer.on('aprs-beacon-sent', l); return () => ipcRenderer.removeListener('aprs-beacon-sent', l); },
  onAprsError: (cb) => { const l = (_e, evt) => cb(evt); ipcRenderer.on('aprs-error', l); return () => ipcRenderer.removeListener('aprs-error', l); }
});
